# Generated by Django 4.2.3 on 2023-07-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(blank=True, null=True)),
                ('hardness', models.FloatField(blank=True, null=True)),
                ('solids', models.FloatField(blank=True, null=True)),
                ('chloramines', models.FloatField(blank=True, null=True)),
                ('sulfate', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('organic_carbon', models.FloatField(blank=True, null=True)),
                ('trihalomethanes', models.FloatField(blank=True, null=True)),
                ('turbidity', models.FloatField(blank=True, null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_probs', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
